###############
## 
####

GPU: [0,1]

VERBOSE: True

MODEL:
  MODE: 'Deraining'
  SESSION: 'CMNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 2 #16
  NUM_EPOCHS: 250
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 5
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: '/home/datasets/T-Cloud/train/'       # path to training data
  VAL_DIR: '/home/datasets/T-Cloud/test/' # path to validation data
  SAVE_DIR: './checkpoints_tcloud'           # path to save models and images
  # SAVE_IMAGES: False
